### ISSUE TITLE
执行命令过程的报错问题

### ISSUE THREAD

**Issue by Chanchiuhung** [yourh/AttentionXML#26]
您好！我在执行“python main.py --data-cnf configure/datasets/EUR-Lex.yaml --model-cnf configure/models/AttentionXML-EUR-Lex.yaml”的时候会显示报错为
/home/jupyter-chanchiuhung/AttentionXML/deepxml/optimizers.py:108: UserWarning: This overload of add_ is deprecated:
        add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
        add_(Tensor other, *, Number alpha) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:1050.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
Traceback (most recent call last):
  File "/home/jupyter-chanchiuhung/AttentionXML/main.py", line 95, in <module>
    main()
  File "/home/jupyter-chanchiuhung/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jupyter-chanchiuhung/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jupyter-chanchiuhung/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jupyter-chanchiuhung/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jupyter-chanchiuhung/AttentionXML/main.py", line 64, in main
    model.train(train_loader, valid_loader, **model_cnf['train'])
  File "/home/jupyter-chanchiuhung/AttentionXML/deepxml/models.py", line 73, in train
    p5, n5 = get_p_5(labels, targets), get_n_5(labels, targets)
  File "/home/jupyter-chanchiuhung/AttentionXML/deepxml/evaluation.py", line 42, in get_precision
    mlb = get_mlb(classes, mlb, targets)
  File "/home/jupyter-chanchiuhung/AttentionXML/deepxml/evaluation.py", line 33, in get_mlb
    mlb = MultiLabelBinarizer(range(targets.shape[1]), sparse_output=True)
TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
请问这是为什么呀？

**Comment by yourh** [comment]
应该是sklearn版本太新了，如果要用新版的sklearn这里要稍微改写一下。

**Comment by Chanchiuhung** [comment]
> 应该是sklearn版本太新了，如果要用新版的sklearn这里要稍微改写一下。

好的，谢谢解答！

**Comment by Chanchiuhung** [comment]
> 应该是sklearn版本太新了，如果要用新版的sklearn这里要稍微改写一下。



> 应该是sklearn版本太新了，如果要用新版的sklearn这里要稍微改写一下。

你好，我使用您提供的Amazon-670K数据集运行模型的时候，在训练集数据train_law_texts.txt处理成train_texts.npy后发现训练样本有454641个，而训练集标签样本有490449个，两者对不上。
从而导致在执行“proprecess.py”时运行到“    if labels is not None:
        assert len(texts) == len(labels)
        np.save(os.path.splitext(label_path)[0], labels)”就会报错。
请问为什么会出现训练样本跟标签的数量对不上这种情况？

**Comment by Chanchiuhung** [comment]
> 应该是sklearn版本太新了，如果要用新版的sklearn这里要稍微改写一下。

你好！请问你能跟我的邮箱取得联系吗？我有些执行精度上的问题希望请教你！这是我的邮箱：chenzhaohong180@gmail.com

**Comment by Chanchiuhung** [comment]
> 



> 应该是sklearn版本太新了，如果要用新版的sklearn这里要稍微改写一下。

抱歉我才看到你的邮箱，我已经跟你联系了，烦请你如果有空的话看一下邮箱，谢谢你！
